#ifndef QBT_ROLL_HEADER
#define QBT_ROLL_HEADER

enum ROLL_OPTION
{
	ROLL_OPTION_UNKNOWN = 0,

	ROLL_OPTION_HUNGERING_ARROW,
	ROLL_OPTION_REDUCE_MELEE_DAMAGE,
	ROLL_OPTION_REDUCE_RANGED_DAMAGE,





	ROLL_OPTION_HEALING_GLOBE,
	ROLL_OPTION_GOLD_PICKUP,
	ROLL_OPTION_EXP,
	ROLL_OPTION_THORN_DAMAGE,
};

enum ROLL_PARAMETER
{
	ROLL_PARAMETER_UNKNOWN = 0,

	ROLL_PARAMETER_15_PERCENT,
	ROLL_PARAMETER_14_PERCENT,
	ROLL_PARAMETER_13_PERCENT,
	ROLL_PARAMETER_12_PERCENT,
	ROLL_PARAMETER_11_PERCENT,
	ROLL_PARAMETER_10_PERCENT,
	ROLL_PARAMETER_07_PERCENT,

};



enum ROLL_ITEM
{
	ROLL_ITEM_UNKNOWN,
	ROLL_ITEM_HUNTERS_WRATH,
};


wchar_t* get_roll_name(ROLL_OPTION);
wchar_t* get_parameter_name(ROLL_PARAMETER);

ROLL_OPTION get_roll_option_01(void);
ROLL_OPTION get_roll_option_02(void);
ROLL_OPTION get_roll_option_03(void);

ROLL_PARAMETER get_roll_parameter_01(void);
ROLL_PARAMETER get_roll_parameter_02(void);
ROLL_PARAMETER get_roll_parameter_03(void);

#endif