#ifndef QBT_ROLL_HEADER
#define QBT_ROLL_HEADER

enum ROLL_OPTION
{
	ROLL_OPTION_UNKNOWN = 0,

	ROLL_OPTION_CRITICAL_HIT_CHANCE,
	ROLL_OPTION_CRITICAL_HIT_DAMAGE,

	ROLL_OPTION_STRENGTH,
	ROLL_OPTION_DEXTERITY,
	ROLL_OPTION_INTELLIGENCE,
	ROLL_OPTION_VITALITY,
	ROLL_OPTION_BASE_DAMAGE,

	ROLL_OPTION_REDUCE_MELEE_DAMAGE,
	ROLL_OPTION_REDUCE_RANGED_DAMAGE,



	ROLL_OPTION_DHSKILL_HUNGERING_ARROW,
	ROLL_OPTION_DHSKILL_BOLAS,
	ROLL_OPTION_DHSKILL_GRENADE,
	ROLL_OPTION_DHSKILL_ENTANGLING_SHOT,
	ROLL_OPTION_DHSKILL_EVASIVE_FIRE,




	ROLL_OPTION_LIFE_PERCENT,
	ROLL_OPTION_LIFE_PER_SECOND,
	ROLL_OPTION_LIFE_HIT,


	ROLL_OPTION_ARMOR,


	ROLL_OPTION_HEALING_GLOBE,
	ROLL_OPTION_GOLD_PICKUP,
	ROLL_OPTION_EXP,
	ROLL_OPTION_THORN_DAMAGE,
};

enum ROLL_PARAMETER
{
	ROLL_PARAMETER_UNKNOWN = 0,
	ROLL_PARAMETER_04_PERCENT,
	ROLL_PARAMETER_04_D_5_PERCENT,
	ROLL_PARAMETER_05_PERCENT,
	ROLL_PARAMETER_05_D_5_PERCENT,
	ROLL_PARAMETER_06_PERCENT,
	ROLL_PARAMETER_07_PERCENT,
	ROLL_PARAMETER_10_PERCENT,
	ROLL_PARAMETER_11_PERCENT,
	ROLL_PARAMETER_12_PERCENT,
	ROLL_PARAMETER_13_PERCENT,
	ROLL_PARAMETER_14_PERCENT,
	ROLL_PARAMETER_15_PERCENT,
};



enum ROLL_ITEM
{
	ROLL_ITEM_UNKNOWN,
	ROLL_ITEM_HUNTERS_WRATH,
	ROLL_ITEM_FOCUS,
};

enum RESOURCE_STATUS
{
	RESOURCE_STATUS_UNKNOWN,
	RESOURCE_STATUS_FULL_FOR_CLOTHES,
};

enum GOLD_STATUS
{
	GOLD_STATUS_UNKNOWN,
	GOLD_STATUS_FULL_FOR_ROLLING,
};

enum ROLL_DESCISION
{
	DESCISION_NOTHING = 0,
	DESCISION_STAY_IN_OPTION_01,
	DESCISION_SELECT_OPTION_01_AND_WAIT_NEXT,
	DESCISION_SELECT_OPTION_02_AND_WAIT_NEXT,
	DESCISION_SELECT_OPTION_02_AND_STOP_ROLL,
	DESCISION_SELECT_OPTION_03_AND_WAIT_NEXT,
	DESCISION_SELECT_OPTION_03_AND_STOP_ROLL,
};


wchar_t* get_roll_name(ROLL_OPTION);


ROLL_OPTION get_roll_option_01(void);
ROLL_OPTION get_roll_option_02(void);
ROLL_OPTION get_roll_option_03(void);

ROLL_PARAMETER get_roll_parameter_01(void);
ROLL_PARAMETER get_roll_parameter_02(void);
ROLL_PARAMETER get_roll_parameter_03(void);
wchar_t* get_parameter_name(ROLL_PARAMETER);


ROLL_ITEM get_roll_item(void);
wchar_t* get_item_name(ROLL_ITEM);


RESOURCE_STATUS get_resource_status(void);
wchar_t* get_resource_info(RESOURCE_STATUS);

GOLD_STATUS get_gold_status(void);
wchar_t* get_gold_info(GOLD_STATUS);


void do_roll(ROLL_ITEM item,
	ROLL_OPTION option_01, ROLL_PARAMETER parameter_01,
	ROLL_OPTION option_02, ROLL_PARAMETER parameter_02,
	ROLL_OPTION option_03, ROLL_PARAMETER parameter_03,
	RESOURCE_STATUS resource_status,
	GOLD_STATUS gold_status);




#endif